In [2]:
import gym
import numpy as np
import random
import time


In [3]:
env = gym.make("FrozenLake-v1")

In [31]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size, action_space_size))

In [32]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
max_episode = 10000
max_step_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
min_exploration_rate = 0.01
max_exploration_rate = 1
decay_rate = 0.01

In [34]:
reward_list = []

# Main loop
for episode in range(max_episode):
    state = env.reset()
    done = False
    reward_current_episode = 0

    for step in range(max_step_per_episode):
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        newstate, reward, done, truncated, info = env.step(action)

        newstate = int(newstate)

        # Update the Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[newstate, :]))
        state = newstate
        reward_current_episode += reward

        if done:
            break

    # Update the exploration rate
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-decay_rate * episode)

    # Add the episode reward to the list
    reward_list.append(reward_current_episode)

# Calculate the average reward per thousand episodes
reward_per_thousand_episode = np.split(np.array(reward_list), max_episode // 1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in reward_per_thousand_episode:
    print(count, ": ", str(sum(r) / 1000))
    count += 1000

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices